### ISSUE TITLE
Run Hadoop instance on AWS

### ISSUE THREAD

**Issue by master-q** [centillion-tech/kick-r#4]

**Comment by master-q** [comment]
First, setup Hadoop on Ubuntu instance. http://www.bogotobogo.com/Hadoop/BigData_hadoop_Install_on_ubuntu_single_node_cluster.php

**Comment by master-q** [comment]
Umm...

```
hduser@ip-10-0-0-85:/usr/local/hadoop$ jps
11077 NameNode
12392 Jps
11464 SecondaryNameNode
hduser@ip-10-0-0-85:/usr/local/hadoop$ netstat -plten | grep java
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:50070           0.0.0.0:*               LISTEN      1001       36280       11077/java      
tcp        0      0 127.0.0.1:54310         0.0.0.0:*               LISTEN      1001       46765       11077/java      
tcp        0      0 0.0.0.0:50090           0.0.0.0:*               LISTEN      1001       46774       11464/java      
hduser@ip-10-0-0-85:/usr/local/hadoop$ hadoop jar ./share/hadoop/mapreduce/hadoop-mapreduce-examples-2.6.0.jar pi 4 100
Number of Maps  = 4
Samples per Map = 100
15/05/08 03:00:09 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/05/08 03:00:10 WARN hdfs.DFSClient: DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /user/hduser/QuasiMonteCarlo_1431054009156_1811178030/in/part0 could only be replicated to 0 nodes instea
d of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1549)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3200)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:641)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:482)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:962)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2039)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2035)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2033)

        at org.apache.hadoop.ipc.Client.call(Client.java:1468)
        at org.apache.hadoop.ipc.Client.call(Client.java:1399)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
        at com.sun.proxy.$Proxy9.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:399)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy10.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1532)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1349)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
```

**Comment by master-q** [comment]
More documents.
- Installing Hadoop on Ubuntu 14 | Institutional Web Page http://disi.unitn.it/~lissandrini/notes/installing-hadoop-on-ubuntu-14.html
- Apache Hadoop 2.5.0 セットアップ手順 その1 – ローカル実行からシングルノードクラスター起動まで | hrendoh's memo http://blog.hrendoh.com/setup-hadoop-single-node-cluster/#.VUw1cupEG00
- Installing the Latest CDH 5 Release https://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_ig_cdh5_install.html
- Cloudera Manager APIを使用したクラスタの自動化 | Hadoopとビッグデータソリューションのリーディングカンパニー | Cloudera Japan http://www.cloudera.co.jp/blog/automating-your-cluster-with-cloudera-manager-api.html
- Cloudera Manager API Client http://cloudera.github.io/cm_api/

**Comment by master-q** [comment]
I think we should use Cloudera Manager.

http://www.cloudera.com/content/cloudera/en/products-and-services/cloudera-enterprise/cloudera-manager.html

**Comment by master-q** [comment]
How to use Cloudera Manager on AWS instance.
1. wget http://archive.cloudera.com/cm5/installer/latest/cloudera-manager-installer.bin
2. chmod u+x cloudera-manager-installer.bin
3. sudo ./cloudera-manager-installer.bin
4. Open http://IP_address:7180 on your web browser

**Comment by master-q** [comment]
Created  branch for Cloudera Manager. https://github.com/centillion-tech/kick-r/tree/feature/cloudera

**Comment by master-q** [comment]
How about Amazon EMR?
- Amazon Elastic MapReduce（Hadoopクラスター Amazon EMR） | アマゾン ウェブ サービス（AWS 日本語） http://aws.amazon.com/jp/elasticmapreduce/
- Amazon Elastic MapReduceの使い方─Hadoopより手軽にはじめる大規模計算：連載｜gihyo.jp … 技術評論社 http://gihyo.jp/dev/serial/01/emr
- MapReduce with R on Hadoop and Amazon EMR | R-bloggers http://www.r-bloggers.com/mapreduce-with-r-on-hadoop-and-amazon-emr/
- Statistical Analysis with Open-Source R and RStudio on Amazon EMR - AWS Big Data Blog https://blogs.aws.amazon.com/bigdata/post/Tx37RSKRFDQNTSL/Statistical-Analysis-with-Open-Source-R-and-RStudio-on-Amazon-EMR
